version: '3.9'

services:
    caddy:
        container_name: core-caddy
        restart: unless-stopped
        image: ghcr.io/htl-grieskirchen-core/caddy-proxy:${TAG:-latest}
        environment:
            DOMAIN_NAME: "${DOMAIN_NAME}"
            TLS_EMAIL: "${TLS_EMAIL}"
        depends_on:
            - backend
            - secure
        volumes:
            - plugin-frontends:/srv/plugins
            - ./mainframe-config.json:/srv/mainframe-config.input.json
            - caddy-data:/data
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        networks:
            - public

    backend:
        container_name: core-backend
        restart: unless-stopped
        image: ghcr.io/htl-grieskirchen-core/plugin-backend:${TAG:-latest}
        environment:
            ConnectionStrings__Production: "server=backend-database;database=core;user=root;password=network-security"
            RSA__public-key: "public-key.pem"
            JWT__Issuer: "https://mainframe.${DOMAIN_NAME}"
            JWT__Audience: "https://mainframe.${DOMAIN_NAME}"
            MainframeOrigin: "https://mainframe.${DOMAIN_NAME}"
        depends_on:
            - backend-database
        volumes:
            - ./public-keys:/app/keys
            - plugin-backends:/app/plugins
        networks:
            - public
            - backend

    backend-database:
        container_name: core-backend-database
        restart: unless-stopped
        image: mariadb:10.10
        environment:
            MARIADB_ROOT_PASSWORD: network-security
        volumes:
            - backend-database-data:/var/lib/mysql
        networks:
            - backend

    secure:
        container_name: core-secure
        restart: unless-stopped
        image: ghcr.io/htl-grieskirchen-core/secure-backend:${TAG:-latest}
        environment:
            ConnectionStrings__Production: "server=secure-database;database=core;user=root;password=network-security"
            MainframeOrigin: "https://mainframe.${DOMAIN_NAME}"
            LDAPConfiguration__ServerIp: "${LDAP_SERVER_IP}"
            JWT__Issuer: "https://mainframe.${DOMAIN_NAME}"
            JWT__Audience: "https://mainframe.${DOMAIN_NAME}"
            RSA__private-key: "private-key.pem"
            RSA__public-key: "public-key.pem"
        depends_on:
            - secure-database
        volumes:
            - ./private-keys:/app/keys
        networks:
            - public
            - secure

    secure-database:
        container_name: core-secure-database
        restart: unless-stopped
        image: mariadb:10.10
        environment:
            MARIADB_ROOT_PASSWORD: network-security
        volumes:
            - secure-database-data:/var/lib/mysql
        networks:
            - secure

    plugin-updater:
        container_name: core-plugin-updater
        restart: unless-stopped
        image: ghcr.io/htl-grieskirchen-core/plugin-updater:${TAG:-latest}
        volumes:
            - ./mainframe-config.json:/data/mainframe-config.json
            - plugin-frontends:/data/plugins/frontend
            - plugin-backends:/data/plugins/backend
            - /var/run/docker.sock:/var/run/docker.sock

    container-updater:
        container_name: core-container-updater
        image: containrrr/watchtower
        restart: unless-stopped
        environment:
            WATCHTOWER_CLEANUP: "true"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - backend

volumes:
    caddy-data:
    backend-database-data:
    secure-database-data:

    plugin-frontends:
    plugin-backends:

networks:
    public:
    backend:
    secure:
